<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-title">{{vm.page_title}}</h1>

                <div ui-view="main_body">
                    <div id="embed-api-auth-container" style="display:block" />
                    <ng-analytics-auth label="Hello" hide-on-auth="true" service-auth-token="{{vm.GAToken}}" auth-container="embed-api-auth-container"></ng-analytics-auth>
                    <ng-analytics-report queries="queries" auth-container="embed-api-auth-container"></ng-analytics-report>
                </div>

                <div class="alert alert-danger" ng-if="vm.error.error">
                    <strong>There was an error: </strong> {{vm.errors.error}}
                    <br>Please go back and login again
                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->
